# vim:ft=kitty

## name: Edgar Morning
## description: Light theme based on the edgar-morning neovim colorscheme

background             #a8a8a8
foreground             #000000
selection_background   #bbbbbb
selection_foreground   #000000
url_color              #006b4f

# Tabs
active_tab_background   #a8a8a8
active_tab_foreground   #000000
inactive_tab_background #a9a9a9
inactive_tab_foreground #5f5f5f

# Windows
active_border_color   #3030a0
inactive_border_color #a9a9a9

# ANSI colours
# normal
color0  #000000
color1  #8b1a1a
color2  #1e6b1e
color3  #6b1fa0
color4  #005555
color5  #9b1f5a
color6  #3030a0
color7  #6e6e6e

# bright
color8  #444444
color9  #8b1a1a
color10 #1e6b1e
color11 #6b1fa0
color12 #005555
color13 #9b1f5a
color14 #3030a0
color15 #000000
