include edgar-morning-theme.conf

font family SourceCodePro Nerd Font
font_size 11.0
modify_font weight 0.12
cursor #222222
cursor_text_color #ffffff
cursor_blink_interval 0
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
scrollback_lines 8000

background   #a8a8a8
foreground   #000000
color0       #000000
color4       #005f5f
color6       #3d2f99
color7       #6e6e6e
color12      #005f5f
color14      #3d2f99
