# look at tmux resurrect

# Ctrl + a 	Command
# Command + t 	New window
# Command + w 	Kill pane
# Command + q 	Kill session
# Command + r 	Reload tmux config
# Command + z 	Zoom to pane
# Command + $ 	Rename session
# Command + , 	Rename window
# Command + g 	Split vertically
# Command + h 	Split horizontally
# Command + ? 	List keyboard shortcuts
# Command + : 	Command prompt
# Command + s 	List sessions


source /usr/share/powerline/bindings/tmux/powerline.conf

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

#Resizing panes:
bind -r j resize-pane -D 2
bind -r k resize-pane -U 2
bind -r h resize-pane -L 2
bind -r l resize-pane -R 2

# use vi mode
setw -g mode-keys vi
set -g status-keys vi
 
# allow utf8 support
setw -g utf8 on

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# set first window to index 1 (not 0) to map more to the keyboard layout
set -g base-index 1
set -g pane-base-index 1

# Keep your finger on ctrl, or don't, same result
bind-key C-d detach-client
bind-key C-p paste-buffer

# Ctrl - t or t new window
unbind t
unbind C-t
bind-key t new-window
bind-key C-t new-window

# Ctrl - w or w to kill panes
unbind w
unbind C-w
bind-key w kill-pane
bind-key C-w kill-pane

# Ctrl + a + n : New session
unbind n
unbind C-n
bind-key n new-session
bind-key C-n new-session

# Show tmux positions in titles
set -g set-titles on<Paste>

# Copy from tmux to system clipboard
# Needs xclip -> sudo apt install xclip
bind -t vi-copy y copy-pipe "xclip -sel clip -i"

